[[jury]]
name = "Andrey Nikulin"
bio = "Faculty member at Núcleo Takinahakỹ de Formação Superior Indígena, Federal University of Goiás, specializing in South American indigenous languages. Ph.D. in Linguistics from University of Brasília. Enjoys reptiles and the traditional music of Trinidad, Venezuela, Brazil, and Bolivia (particularly calypso and tecnobrega)."
photo = "/who/jury/AN.jpg"
initials = "AN"
member_since = "2018"
iol_contestant_in = "2008, 2009 and 2010"

[[jury]]
name = "Alexander Piperski"
bio = "Moscow Traditional Linguistics Olympiad and APLO committee member. Senior lecturer at the Slavic Department at Stockholm University, research fellow at the Сhair of Computational Сorpus Linguistics at Friedrich-Alexander-University Erlangen-Nuremberg. Fond of public transport and cannoli siciliani."
photo = "/who/jury/AP.jpg"
initials = "AP"
member_since = "2006"
iol_contestant_in = "2004 and 2005"

[[jury]]
name = "Boris Iomdin"
bio = "Linguist specializing in lexicography and semantics, teaching linguistics and languages to children, high school, and university students in Russian, English, German, and Hebrew. Author of hundreds of linguistic problems, including 17 at the IOL. A fan of playing linguistic games, reading books, and researching linguistic games in books. www.borisiomdin.com"
photo = "/who/jury/BI.jpeg"
initials = "BI"
member_since = "2003"

[[jury]]
name = "Dmitry Gerasimov"
bio = "Research engineer at Institut national des langues et civilisations orientales."
photo = "/who/jury/DG.jpg"
initials = "DG"
member_since = "2005"

[[jury]]
name = "Dan-Mircea Mirea"
bio = "PhD candidate in Psychology at Princeton University, undergraduate and Masters' from University of Cambridge. Linguistics & psychology content creator @danniesbrain on TikTok and Instagram. Big fan of singing (karaoke included), video/board games, Eurovision, and all things historical."
photo = "/who/jury/DMM.jpg"
initials = "DM"
member_since = "2019"
iol_contestant_in = "2014 and 2015"

[[jury]]
name = "Elysia Warner"
bio = "UKLO committee member. Studied Chinese and Linguistics at the University of Cambridge. Tax specialist for HM Government. Enjoys knitting, cryptic crosswords, and Bollywood dancing."
photo = "/who/jury/EW.jpg"
initials = "EW"
member_since = "2018"
iol_contestant_in = "2013 and 2014"

[[jury]]
name = "Hugh Dobbs"
bio = "AILO committee member. Retired teacher at Newtown School (Waterford, Ireland). "
photo = "/who/jury/HND.JPG"
initials = "HND"
member_since = "2010"

[[jury]]
name = "Ivan Derzhanski"
bio = "PhD (Cognitive Science, Edinburgh). Associate professor (Institute for Mathematics and Informatics, Bulgarian Academy of Sciences); does research in theoretical linguistics, lectures in computational linguistics, natural language processing and Python programming. Singlehandedly in charge of the Olympiad in Linguistics in Bulgaria (since 1998). Co-founder of IOL (2003)."
photo = "/who/jury/ID.jpg"
initials = "ID"
member_since = "2003"

[[jury]]
name = "Jan Petr"
bio = "PhD student in Mathematics at the University of Cambridge. Member of the organizing team of ČLO. Fond of puzzles and games of various sorts, of learning and teaching, and of playing ultimate frisbee."
photo = "/who/jury/JP.jpg"
initials = "JP"
member_since = "2021"
iol_contestant_in = "2015, 2016 and 2017"

[[jury]]
name = "Ksenia Gilyarova"
bio = "Associate Professor at the Institute of Linguistics, Russian State University for the Humanities. Authored ten problems for the IOL, five of which received the Solvers' Choice award. Parenting three kids. Enjoys hiking, jogging, and writing."
photo = "/who/jury/KG.jpg"
initials = "KG"
member_since = "2003"

[[jury]]
name = "Liam McKnight"
bio = "Studied Linguistics at the University of Cambridge, and now works in academic publishing. Linguistic interests include syntax, Chinese, pronouns and Irish; non-linguistic interests include improvised comedy/theatre and food of all kinds."
photo = "/who/jury/LM.jpg"
initials = "LM"
member_since = "2019"
iol_contestant_in = "2015, 2016, 2017 and 2018"

[[jury]]
name = "Aleksejs Peguševs"
bio = "Composer of music and linguistic problems, educator, mind sports athlete (mainly competitive Carcassonne). Masters in Linguistics from University of Oxford (2018) and Masters in Music from Sibelius Academy, Finland (2017)."
photo = "/who/jury/LP.jpg"
initials = "LP"
member_since = "2012"
iol_contestant_in = "2008, 2009 and 2010"

[[jury]]
name = "Maria Rubinstein"
bio = "Moscow Traditional Linguistics Olympiad Problem Committee member since 1997, IOL Problem Committee member since the beginning. Working on Israeli Linguistics Olympiad. And a hobbyist photographer."
photo = "/who/jury/MR.png"
initials = "MR"
member_since = "2003"

[[jury]]
name = "Milena Veneva"
bio = "Applied mathematician. Bulgarian National Olympiad in Linguistics Problem Committee member since 2010. Enjoys travelling, reading books, and sport."
photo = "/who/jury/MV.jpg"
initials = "MV"
member_since = "2013"

[[jury]]
name = "Przemysław Podleśny"
bio = "MA student of Estonian and Finno-Ugric languages at the University of Tartu. Bachelor's degree in Computer Science and former student of Baltic Philology, Classical Philology, Ethnology at the University of Warsaw. In the past years contributed to Polish and Estonian LOs. A fan of challenges, puzzles, languages, words, sounds, letters and their more or less artful arrangements."
photo = "/who/jury/PP.jpg"
initials = "PP"
member_since = "2021"
iol_contestant_in = "2017 and 2018"

[[jury]]
name = "Tung-Le Pan"
bio = "APLO and HKLO (Hong Kong; also co-founder) Problem Committee member. MA student in linguistics at the National Taiwan University. Enjoys tasting all kinds of beverages. Currently learning how to handstand, among other useless skills."
photo = "/who/jury/PT.jpg"
initials = "PT"
member_since = "2018"
iol_contestant_in = "2017 and 2018"

[[jury]]
name = "Stanislav Gurevich"
bio = "One of the organizers of Spanish LO. Founder (2001) and permanent director of Traditional Linguistics Summer School in Estonia. Passionate fan of seasonal mushroom-hunting. "
photo = "/who/jury/SG.jpg"
initials = "SG"
member_since = "2004"

[[jury]]
name = "Shinjini Ghosh"
bio = "APLO and PLO (India) Problem Committee member. Undergraduate in Computer Science and Linguistics, followed by MEng from Massachusetts Institute of Technology. Enjoys painting, Indian classical dance, cooking, and board games."
photo = "/who/jury/SGH.png"
initials = "SGH"
member_since = "2018"
iol_contestant_in = "2016, 2017 and 2018"

[[jury]]
name = "Taehun Lee"
bio = "Visiting Assistant Professor in the Department of Slavic Languages and Literatures at Northwestern University. Research and Teaching include Comparative and World Literature---namely Russian, Turkish, and Japanese Literatures."
photo = "/who/jury/TL.jpg"
initials = "TL"
member_since = "2009"
iol_contestant_in = "2008"

[[jury]]
name = "Yuyang Liu"
bio = "China LO Problem Committee member. PhD student in Linguistics at Yale University."
photo = "/who/jury/YL.jpg"
initials = "YL"
member_since = "2021"
iol_contestant_in = "2016 and 2017"
