[[items]]
title = "<a href=\"/where/#city-tour\">City Tour program announced. Fill in the form until <strong>July 16</strong></a>"
date = "Jul 12, 2024"

[[items]]
title = "<a href=\"/who/#participants\">Participant list</a> updated"
date = "May 08, 2024"

[[items]]
title = "<a href=\"/how/#registration\">Registration</a> deadlines postponed"
date = "Apr 30, 2024"

[[items]]
title = "<a href=\"/who/#problem-committee-and-jury\">International Jury</a> announced"
date = "Apr 02, 2024"

[[items]]
title = "Final <a href=\"/who/#volunteers\">volunteer selection</a> announced"
date = "Mar 25, 2024"

[[items]]
title = "<a href=\"/how/#registration\">Standard Registration</a> opened"
date = "Feb 27, 2024"

[[items]]
title = "<a href=\"/how/#registration\">Early Bird registration</a> opened"
date = "Jan 28, 2024"

[[items]]
title = "<a href=\"/when/#teacher-s-program\">Proposal submissions</a> for the Teacher's Program opened"
date = "Jan 23, 2024"

[[items]]
title = '<a href="/who/#volunteers">Volunteer application</a> opened'
date = "Jan 21, 2024"

[[items]]
title = "Website officially launched"
date = "Jan 21, 2024"
