[[items]]
title = "Final <a href=\"/how/#volunteers\">volunteer selection</a> announced"
date = "Mar 25, 2024"

[[items]]
title = "<a href=\"/how/#registration\">Standard Registration</a> opened"
date = "Feb 27, 2024"

[[items]]
title = "<a href=\"/how/#registration\">Early Bird registration</a> opened"
date = "Jan 28, 2024"

[[items]]
title = "<a href=\"/when/#teacher-s-program\">Proposal submissions</a> for the Teacher's Program opened"
date = "Jan 23, 2024"

[[items]]
title = '<a href="/who/#volunteers">Volunteer application</a> opened'
date = "Jan 21, 2024"

[[items]]
title = "Website officially launched"
date = "Jan 21, 2024"
