[[days]]
name = "July 23"
weekday = "Tue"
[[days.activities]]
name = "Arrivals"
start = 6
duration = 16

[[days]]
name = "July 24"
weekday = "Wed"
[[days.activities]]
name = "Opening Ceremory"
start = 7
duration = 2
[[days.activities]]
name = "Integration Games"
start = 12
duration = 3

[[days]]
name = "July 25"
weekday = "Thu"
[[days.activities]]
name = "IOLwiki"
start = 10
duration = 4
[[days.activities]]
name = "City Tour"
start = 10
duration = 10

[[days]]
name = "July 26"
weekday = "Fri"
[[days.activities]]
name = "<strong>Individual Contest</strong>"
start = 9
duration = 6
[[days.activities]]
name = "Party"
start = 18
duration = 4

[[days]]
name = "July 27"
weekday = "Sat"
[[days.activities]]
name = "Excursion"
start = 8
duration = 10

[[days]]
name = "July 28"
weekday = "Sun"
[[days.activities]]
name = "Cultural and Learning activities in Brasília"
start = 8
duration = 10

[[days]]
name = "July 29"
weekday = "Mon"
[[days.activities]]
name = "<strong>Team Contest</strong>"
start = 9
duration = 6
[[days.activities]]
name = "IOL Quiz"
start = 18
duration = 2

[[days]]
name = "July 30"
weekday = "Tue"
[[days.activities]]
name = "Solution Presentation"
start = 9
duration = 3
[[days.activities]]
name = "Closing Ceremony"
start = 13
duration = 2
[[days.activities]]
name = "IOL's Got Talent"
start = 16
duration = 2
[[days.activities]]
name = "Farewell Party"
start = 19
duration = 3

[[days]]
name = "July 31"
weekday = "Wed"
[[days.activities]]
name = "Departures"
start = 6
duration = 16

[[timevalues]]
time = "6:00"
[[timevalues]]
time = "7:00"
[[timevalues]]
time = "8:00"
[[timevalues]]
time = "9:00"
[[timevalues]]
time = "10:00"
[[timevalues]]
time = "11:00"
[[timevalues]]
time = "12:00"
[[timevalues]]
time = "13:00"
[[timevalues]]
time = "14:00"
[[timevalues]]
time = "15:00"
[[timevalues]]
time = "16:00"
[[timevalues]]
time = "17:00"
[[timevalues]]
time = "18:00"
[[timevalues]]
time = "19:00"
[[timevalues]]
time = "20:00"
[[timevalues]]
time = "21:00"
[[timevalues]]
time = "22:00"
