[[days]]
name = "23/07"
weekday = "terça-feira"

[[days.activities]]
periodTime = "Manhã"
name = "O que são olimpíadas de linguística? Como resolver problemas de linguística? Como eles impactam a sala de aula?"
who = "Bruno L’Astorina (Olimpíada Brasileira de Linguística) <br> Rodrigo Tiradentes (Olimpíada Brasileira de Linguística) <br> Eloisa Pilati (UnB) <br> Janaina Weissheimer (UFRN / Rede CpE) <br> Ivan Derjanski (Academia Búlgara de Ciências – Sofia) (Olimpíada de Linguística da Bulgária)"

[[days.activities]]
periodTime = "Tarde"
name = "Línguas e culturas indígenas"



[[days]]
name = "24/07"
weekday = "quarta-feira"

[[days.activities]]
periodTime = "Manhã"
name = "Visita à IOL"

[[days.activities]]
start = "14h"
end = "18h"
periodTime = "Tarde"
name = "Cerimônia de Abertura da IOL"



[[days]]
name = "25/07"
weekday = "quinta-feira"

[[days.activities]]
start = "8h"
end = "10h"
periodTime = "Manhã"
name = "Consciência metalinguística e aprendizagem ativa"
who = "Eloisa Pilati (UnB) <br> Bruno L’Astorina (Olimpíada Brasileira de Linguística)"

[[days.activities]]
start = "10h30"
end = "11h"
periodTime = "Tarde"
name = "Usando tradutores online gratuitos com aprendizes de línguas"
who = "Harold Somers (Prof. emérito da Universidade de Manchester) (Olimpíada de Linguística da Irlanda) <br> *com tradução consecutiva"

[[days.activities]]
start = "11h"
end = "12h"
periodTime = "Tarde"
name = "Multilinguismo na sociedade e na escola: exemplos da Alemanha e do Brasil"
who = "Janaina Weissheimer (UFRN / Rede CpE) <br> Nathalie Topaj (Centro Leibniz de Ciências da Linguagem) (Olimpíada de Linguística da Alemanha)"

