[[days]]
name = "July 23"
weekday = "Tue"
[[days.activities]]
name = "Arrivals"

[[days]]
name = "July 24"
weekday = "Wed"
[[days.activities]]
name = "Opening Ceremory"
[[days.activities]]
name = "Integration Games"

[[days]]
name = "July 25"
weekday = "Thu"
[[days.activities]]
name = "IOLwiki"
[[days.activities]]
name = "City Tour"

[[days]]
name = "July 26"
weekday = "Fri"
[[days.activities]]
name = "<strong>Individual Contest</strong>"
[[days.activities]]
name = "Party"

[[days]]
name = "July 27"
weekday = "Sat"
[[days.activities]]
name = "Excursion"

[[days]]
name = "July 28"
weekday = "Sun"
[[days.activities]]
name = "Cultural and Learning activities in Brasília"

[[days]]
name = "July 29"
weekday = "Mon"
[[days.activities]]
name = "<strong>Team Contest</strong>"
[[days.activities]]
name = "IOL Quiz"

[[days]]
name = "July 30"
weekday = "Tue"
[[days.activities]]
name = "Solution Presentation"
[[days.activities]]
name = "Closing Ceremony"
[[days.activities]]
name = "IOL's Got Talent"
[[days.activities]]
name = "Farewell Party"

[[days]]
name = "July 31"
weekday = "Wed"
[[days.activities]]
name = "Departures"