[[days]]
name = "July 23"
weekday = "Tue"
[[days.activities]]
name = "Arrivals <br>Registering"
start = 6
duration = 16

[[days]]
name = "July 24"
weekday = "Wed"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "Integration Games"
start = 8.5
duration = 2.5
[[days.activities]]
name = "Lunch with Ambassadors"
start = 11.5
duration = 3.5
[[days.activities]]
name = "Opening Lecture"
start = 15.5
duration = 1
[[days.activities]]
name = "Dinner"
start = 17
duration = 1
[[days.activities]]
name = "Opening Ceremory"
start = 19
duration = 2.5

[[days]]
name = "July 25"
weekday = "Thu"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "IOLwiki"
start = 8.7
duration = 3.3
[[days.activities]]
name = "Lunch"
start = 12.5
duration = 1.5
[[days.activities]]
name = "City Tour"
start = 14
duration = 4
[[days.activities]]
name = "Dinner"
start = 18
duration = 1.5
[[days.activities]]
name = "Brasília Orchestra"
start = 20
duration = 1.5

[[days]]
name = "July 26"
weekday = "Fri"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "<strong>Individual Contest</strong>"
start = 9
duration = 6
[[days.activities]]
name = "June festivities"
start = 17
duration = 4

[[days]]
name = "July 27"
weekday = "Sat"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "Excursion"
start = 8
duration = 10
[[days.activities]]
name = "Dinner"
start = 18
duration = 1.5

[[days]]
name = "July 28"
weekday = "Sun"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "Indigenous Culture Activities"
start = 8.5
duration = 3
[[days.activities]]
name = "Lunch + City Walk"
start = 12
duration = 4
[[days.activities]]
name = "Dinner"
start = 18
duration = 2

[[days]]
name = "July 29"
weekday = "Mon"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "<strong>Team Contest</strong>"
start = 9
duration = 4
[[days.activities]]
name = "Lunch"
start = 13
duration = 1.5
[[days.activities]]
name = "Lecture"
start = 16
duration = 1
[[days.activities]]
name = "Dinner"
start = 18
duration = 1.5
[[days.activities]]
name = "IOL Quiz"
start = 20
duration = 2

[[days]]
name = "July 30"
weekday = "Tue"
[[days.activities]]
name = "Breakfast"
start = 6
duration = 2
[[days.activities]]
name = "Problem Solutions"
start = 9
duration = 1.5
[[days.activities]]
name = "Lunch"
start = 12
duration = 2
[[days.activities]]
name = "Closing Ceremony"
start = 15
duration = 2.5
[[days.activities]]
name = "Farewell Party"
start = 19.5
duration = 2.5

[[days]]
name = "July 31"
weekday = "Wed"
[[days.activities]]
name = "Departures"
start = 6
duration = 16

[[timevalues]]
time = "6:00"
[[timevalues]]
time = "7:00"
[[timevalues]]
time = "8:00"
[[timevalues]]
time = "9:00"
[[timevalues]]
time = "10:00"
[[timevalues]]
time = "11:00"
[[timevalues]]
time = "12:00"
[[timevalues]]
time = "13:00"
[[timevalues]]
time = "14:00"
[[timevalues]]
time = "15:00"
[[timevalues]]
time = "16:00"
[[timevalues]]
time = "17:00"
[[timevalues]]
time = "18:00"
[[timevalues]]
time = "19:00"
[[timevalues]]
time = "20:00"
[[timevalues]]
time = "21:00"
[[timevalues]]
time = "22:00"
