[[days]]
name = "23/07"
weekday = "terça-feira"

[[days.activities]]
name = "Credenciamento"
periodTime = "Manhã"
start = "7h"
end = "8h"

[[days.activities]]
start = "8h"
end = "8h45"
periodTime = "Manhã"
name = "Abertura - Boas-vindas ao Universo Olímpico "

[[days.activities]]
start = "8h45"
end = "9h45"
periodTime = "Manhã"
name = "Palestra - Conhecendo as Olimpíadas de Linguística"
who = "Bruno L’Astorina (Olimpíada Brasileira de Linguística) <br> Rodrigo Tiradentes (Olimpíada Brasileira de Linguística)"

[[days.activities]]
start = "10h"
end = "12h"
periodTime = "Manhã"
name = "Oficina - Problemas de linguística em sala de aula"
who = "Rodrigo Tiradentes (OBL / Olimpíada Brasileira de Linguística)"

[[days.activities]]
start = "13h30"
end = "15h"
periodTime = "Tarde"
name = "Oficina - Problemas de linguística"
who = "Ivan Derjanski (Academia Búlgara de Ciências – Sofia) (Olimpíada de Linguística da Bulgária) <br> *em Português"

[[days.activities]]
start = "15h30"
end = "17h"
periodTime = "Tarde"
name = "Palestra - Línguas e culturas indígenas no ensino escolar"

[[days]]
name = "24/07"
weekday = "quarta-feira"

[[days.activities]]
start = "14h"
end = "18h"
periodTime = "Tarde"
name = "Cerimônia de Abertura da IOL"


[[days]]
name = "25/07"
weekday = "quinta-feira"

[[days.activities]]
start = "8h"
end = "10h"
periodTime = "Manhã"
name = "Oficina - Consciência metalinguística e aprendizagem ativa"
who = "Prof. Eloisa Pilati (UnB) <br> Bruno L’Astorina (Olimpíada Brasileira de Linguística)"

[[days.activities]]
start = "10h30"
end = "11h"
periodTime = "Tarde"
name = "Oficina - Usando tradutores online gratuitos com aprendizes de línguas"
who = "Harold Somers (Prof. emérito da Universidade de Manchester) (Olimpíada de Linguística da Irlanda) <br> *com tradução consecutiva"

[[days.activities]]
start = "11h"
end = "12h"
periodTime = "Tarde"
name = "Palestra - Multilinguismo na sociedade e na escola: exemplos da Alemanha e do Brasil"
who = "Janaina Weissheimer (UFRN / Rede CpE) <br> Nathalie Topaj (Centro Leibniz de Ciências da Linguagem) (Olimpíada de Linguística da Alemanha)"

[[days.activities]]
name = "Encerramento"
periodTime = "Tarde"