[[countries]]
name = "Brazil"
flag = "/country_flags/brazil.png"

[[countries]]
name = "United Kingdom"
flag = "/country_flags/uk.png"
observers = [
  "Daniel Turaev",
]

[[countries.teams]]
name = "United Kingdom"
team_leader = "Simi Hellsten"
participants = [
  "Alison Craig-Greene",
  "Max Fisher-Ayres",
  "Yipeng Xu",
  "Zachary Yen",
]

[[countries]]
name = "Thailand"
flag = "/country_flags/thailand.png"
observers = [
  "Natchanan Natpratan",
]

[[countries.teams]]
name = "Thailand"
team_leader = "Nattanun Chanchaochai"
participants = [
  "Pitchayapa Cusinsup",
  "Siravit Sriboonjareanchai",
  "Narongrith Artnarongrith",
  "Tanupat Trakulthongchai",
]

[[countries]]
name = "Ukraine"
flag = "/country_flags/ukraine.png"

[[countries.teams]]
name = "Ukraine"
team_leader = "Tamila Krashtan"
participants = [
  "Ostap Drushchak",
  "Denys Tereshchenko",
  "Oleksandra Gol'dina",
  "Kateryna Berehulyak",
]

[[countries]]
name = "Ireland"
flag = "/country_flags/ireland.png"
observers = [
  "Harold Somers",
]

[[countries.teams]]
name = "Ireland"
team_leader = "Cara Tighe"
participants = [
  "Dáithí Butler",
  "Paddy Clancy",
  "Eliška Dvořáková",
  "Patrick Chen",
]

[[countries]]
name = "Germany"
flag = "/country_flags/germany.png"

[[countries]]
name = "Australia"
flag = "/country_flags/australia.png"

[[countries]]
name = "Malaysia"
flag = "/country_flags/malaysia.png"

[[countries]]
name = "China"
flag = "/country_flags/china.png"

[[countries]]
name = "Colombia"
flag = "/country_flags/colombia.png"

[[countries]]
name = "Bangladesh"
flag = "/country_flags/bangladesh.png"

[[countries]]
name = "Latvia"
flag = "/country_flags/latvia.png"
observers = [
  "Ata Krūmiņa",
]

[[countries.teams]]
name = "Latvia"
team_leader = "Vladimirs Ļitvinskis"
participants = [
  "Anna Loseva",
  "Borislavs Konstantins Kučiks",
  "Maksims Hodosevičs",
  "Varvara Gromova",
]

[[countries]]
name = "Finland"
flag = "/country_flags/finland.png"

[[countries]]
name = "Japan"
flag = "/country_flags/japan.png"

[[countries]]
name = "Republic of Korea"
flag = "/country_flags/south_korea.webp"

[[countries]]
name = "Taiwan"
flag = "/country_flags/taiwan.png"

[[countries]]
name = "Slovenia"
flag = "/country_flags/slovenia.png"

[[countries.teams]]
name = "Slovenia"
team_leader = "Simona Klemenčič"
participants = [
  "Patricia Király",
  "Brest Lenarčič",
  "Bruno Žižmund",
  "Nives Gošnjak",
]

[[countries]]
name = "Republic of Moldova"
flag = "/country_flags/moldova.png"

[[countries]]
name = "Kazakhstan"
flag = "/country_flags/kazakhstan.png"

[[countries]]
name = "Poland"
flag = "/country_flags/poland.png"

[[countries]]
name = "Canada Anglophone"
flag = "/country_flags/canada.png"

[[countries]]
name = "Estonia"
flag = "/country_flags/estonia.png"

[[countries.teams]]
name = "Estonia"
team_leader = "Linda Freienthal"
participants = [
  "Lisette-Liis Loorits",
  "Margetta Pajuste",
  "Karl-Erik Volberg",
  "Margaret Braun",
]

[[countries]]
name = "Netherlands"
flag = "/country_flags/netherlands.png"


[[countries]]
name = "Vietnam"
flag = "/country_flags/vietnam.png"

[[countries]]
name = "United States of America"
flag = "/country_flags/usa.png"

[[countries]]
name = "Hungary"
flag = "/country_flags/hungary.png"

[[countries]]
name = "India"
flag = "/country_flags/india.png"

[[countries]]
name = "Israel"
flag = "/country_flags/israel.png"

[[countries.teams]]
name = "Israel"
team_leader = "Sophya Welle"
participants = [
  "Lev Ianushevich",
  "Roman Roginsky",
  "Martha Vogman",
  "Olya Besova",
]

[[countries]]
name = "Czechia"
flag = "/country_flags/czechia.png"

[[countries.teams]]
name = "Czechia"
team_leader = "Michaela Svatošová"
participants = [
  "Vít Černý",
  "Richard Dobíšek",
  "Miroslav Havel",
  "Matěj Čapka",
]

[[countries]]
name = "Bulgaria"
flag = "/country_flags/bulgaria.png"

[[countries]]
name = "Hong Kong"
flag = "/country_flags/hong_kong.png"
observers = [
  "Ian Tam", # Tam Lok Hang
]

[[countries.teams]]
name = "Hong Kong"
team_leader = "Vlad A. Neacșu" # Vlad-Andrei Neacșu
participants = [
  "Choi John Nathaniel", # Choi John Nathaniel
  "Daniel Lin", # Lin Cheuk Hang
  "Henry Wong", # Wong Tok Shing Henry
  "Maxwell Ji", # Ji Shu Ching
]

[[countries]]
name = "Switzerland"
flag = "/country_flags/switzerland.png"

[[countries]]
name = "Canada Francophone"
flag = "/country_flags/canada_fr.png"

[[countries.teams]]
name = "Canada (FR)"
team_leader = "Corinne Soucy"
participants = [
  "Jonah Janzen",
  "Mingzhe Li",
  "Serine Shin",
  "Jade Diwan",
]

[[countries]]
name = "Belka Team"
flag = "/country_flags/belka_team.png"
observers = [
  "Anastasiia Puchkova",
]

[[countries.teams]]
name = "Belka Team"
team_leader = "Aleksey Starchenko"
participants = [
  "Nadežda Efremova	",
  "Ekaterina Churkina",
  "Eleonora Stepanova",
  "Mixail Nikitin",
]

[[countries]]
name = "Nepal"
flag = "/country_flags/nepal.png"
no_box_shadow = true

[[countries]]
name = "Iran"
flag = "/country_flags/iran.png"

[[countries.teams]]
name = "Iran (Islamic Republic of)"
team_leader = "Hossein Ghasempour Moghaddam"
participants = [
  "Amir Mahdi Jamshidiha",
  "Farnam Ahmadian",
  "Sara Toor",
  "Mohammad Hassan Zare Bidaki",
]

[[countries]]
name = "Sweden"
flag = "/country_flags/sweden.png"

[[countries.teams]]
name = "Sweden Älg"
team_leader = "Emil Ingelsten"
participants = [
  "Elisabet Xie",
  "Jacob Strömgård",
  "Elvin Runeson",
  "Adam Ahlberg",
]

[[countries.teams]]
name = "Sweden Mård"
team_leader = "Louise Malm"
participants = [
  "Moaaz Saad",
  "Markus Farnebäck",
  "William Eriksson",
  "Allan Ismail",
]

[[countries]]
name = "Portugal"
flag = "/country_flags/portugal.png"

[[countries]]
name = "Romania"
flag = "/country_flags/romania.png"

[[countries]]
name = "Malta"
flag = "/country_flags/malta.png"

[[countries]]
name = "Philippines"
flag = "/country_flags/philippines.png"
observers = [
  "Emerita Danac",
]

[[countries.teams]]
name = "Philippines"
team_leader = "Maria Victorina Rada"
participants = [
  "Sandrene Rylie Sy",
  "Maddigan Hailey Sy",
  "Rainier Roi Tayam",
  "Erika Fiel Danac",
]
